<?php

namespace app\modules\addressbook\admin;

use luya\admin\components\AdminMenuBuilder;
use luya\base\CoreModuleInterface;

/**
 * Addressbook Admin Module.
 *
 * File has been created with `module/create` command on LUYA version 1.0.0.
 */
class Module extends \luya\admin\base\Module implements CoreModuleInterface
{

    public $apis = [
        'api-addressbook-contact' => 'app\modules\addressbook\admin\apis\ContactController',
        'api-addressbook-group' => 'app\modules\addressbook\admin\apis\GroupController'
    ];


    public $dashboardObjects = [
        [
            'class' => 'luya\admin\dashboard\BasicDashboardObject',
            'outerTemplate' => '
                    <div class="card-image">
                        <img src="http://www.loveo.cc/wp-content/uploads/2017/02/card-image.jpg"
                             alt="Orange"/>
                        <div class="card-header"><h3>{{title}}</h3></div>
                    </div>
                    <div class=""><ul class="list-group list-group-flush">{{template}}</ul></div>',
            'template' => '<li class="list-group-item" ng-repeat="item in data"><p>{{item.salutation}}</p></li>',
            'dataApiUrl' => 'admin/api-addressbook-contact',
            'title' => 'The Users',
        ],
    ];

    public function getMenu()
    {
        return (new AdminMenuBuilder($this))->node(static::t('Contact'), 'contacts')
            ->group(static::t('Menu'))
            ->itemApi(static::t('Contact'), 'addressbookadmin/contact/index', 'label', 'api-addressbook-contact')
            ->itemApi(static::t('Group'), 'addressbookadmin/group/index', 'label', 'api-addressbook-group');
    }


    /**
     * @inheritdoc
     */
    public static function onLoad()
    {
        self::registerTranslation('addressbook*', static::staticBasePath() . '/messages', [
            'addressbook' => 'addressbook.php',
        ]);
    }

    public function getAdminAssets()
    {
        return [
            'app\assets\DashboardAsset',
        ]; // TODO: Change the autogenerated stub
    }


    /**
     * Translations for CMS Module.
     *
     * @param unknown $message
     * @param array $params
     * @return string
     */
    public static function t($message, array $params = [])
    {
        return parent::baseT('addressbook', $message, $params);
    }


}